default_platform(:ios)

platform :ios do
  before_all do
    # 서버 환경에 따라 Xcode를 유연하게 선택 (yml에서 설정하므로 주석 처리 가능)
    # xcode_select("/Applications/Xcode.app")
  end

  desc "유닛 테스트 실행 (CI용)"
  lane :test do
    scan(
      project: "Zest.xcodeproj",
      scheme: "Zest",
      device: "iPhone 16 Pro",
      xcargs: "-allowProvisioningUpdates -destination 'platform=iOS Simulator,name=iPhone 16 Pro' CODE_SIGNING_ALLOWED=NO",
      clean: true,
      fail_build: true
    )
  end

  desc "TestFlight에 베타 빌드 배포 (CD용)"
  lane :beta do
    # 배포 시에만 API Key가 필요하므로 여기서 체크합니다.
    UI.user_error!("API_KEY_ID missing") if ENV["APP_STORE_CONNECT_API_KEY_ID"].nil?
    
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"],
      is_key_content_base64: false
    )

    increment_build_number(xcodeproj: "Zest.xcodeproj")

    build_app(
      project: "Zest.xcodeproj",
      scheme: "Zest",
      export_method: "app-store",
      export_xcargs: "-allowProvisioningUpdates",
      export_team_id: "A3GL2XU4F8"
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true,
      skip_submission: true
    )
  end
end
