# fastlane/Fastfile

default_platform(:ios)

platform :ios do
  
  # 모든 레인 실행 전에 API Key를 설정합니다.
  before_all do
    if !is_ci
      xcode_select("/Applications/Xcode.app")
    end

  end

  desc "유닛 테스트 실행 (CI용)"
  lane :test do
  
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "100"
    ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"] = "5"
    
    scan(
      project: "Zest.xcodeproj", # Workspace 에러 방지
      scheme: "Zest",
      fail_build: true,
      prelaunch_simulator: true,
      xcargs: "CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO",
      destination: ENV['CI_MODE'] ? "platform=iOS Simulator,name=iPhone 16,OS=18.6" : nil,
      device: ENV['CI_MODE'] ? nil : "iPhone 16 Pro",
      clean: false
    )
  end

  desc "TestFlight에 베타 빌드 배포 (CD용)"
  lane :beta do
    # 환경 변수가 있는지 먼저 확인하고 없을 경우 에러 메시지 출력
    UI.user_error!("API_KEY_ID missing") if ENV["APP_STORE_CONNECT_API_KEY_ID"].nil?
    
    # GitHub Secrets에서 가져온 환경변수를 사용하여 인증 객체를 생성합니다.
      api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"],
      is_key_content_base64: false # .p8 파일 내용 그대로 사용할 경우 false
    )
    # 1. 빌드 번호 자동 증가 (Xcode 설정 필요)
    increment_build_number(xcodeproj: "Zest.xcodeproj")

    # 2. 앱 빌드 (Archive)
    build_app(
      project: "Zest.xcodeproj", # SPM 사용자용 설정 (workspace 대신 사용)
      scheme: "Zest",
      include_bitcode: false,
      export_method: "app-store",
      export_xcargs: "-allowProvisioningUpdates",
      export_team_id: "A3GL2XU4F8"
    )

    # 3. TestFlight 업로드
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true, # CI 효율을 위해 대기 생략
      skip_submission: true # 심사 제출은 수동으로 하기 위해 생략
    )
  end

  # 에러 발생 시 알림 (선택 사항)
  error do |lane, exception|
    # Slack 알림 등을 여기에 추가할 수 있습니다.
  end
end

